# Generated by Django 5.1.7 on 2025-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_comment', models.CharField(max_length=200)),
                ('date_comment', models.DateTimeField()),
                ('content_comment', models.TextField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recomendación de libro',
                'verbose_name_plural': 'Recomendaciones de libros',
                'ordering': ['-date_comment'],
            },
        ),
    ]
